### ISSUE TITLE
error when an input mapping has a joinCondition

### ISSUE THREAD

**Issue by dachafra** [SDM-TIB/ISWC2020RMLFnQ#4]
When a mapping has an rr:joinCondition in a POM, FunMap produces an error:
```
Traceback (most recent call last):
  File "run_translator.py", line 3, in <module>
    translate(str(sys.argv[1]))
  File "/Users/dchaves/Documents/proyectos/tib/FunMap/translator/translate.py", line 362, in translate
    reader = pd.read_csv(triples_map.data_source, usecols=fields.keys())
  File "/Users/dchaves/anaconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 702, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/Users/dchaves/anaconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 429, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/Users/dchaves/anaconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 895, in __init__
    self._make_engine(self.engine)
  File "/Users/dchaves/anaconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 1122, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/Users/dchaves/anaconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 1895, in __init__
    _validate_usecols_names(usecols, self.orig_names)
  File "/Users/dchaves/anaconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 1237, in _validate_usecols_names
    "columns expected but not found: {missing}".format(missing=missing)
ValueError: Usecols do not match columns, columns expected but not found: ['http://MapFun.KG/#idRoute']
```

The zip file contains 2 csvs, 1 mapping and the functions.py with the new function implemented.
[data.zip](https://github.com/SDM-TIB/FunMap/files/5189086/data.zip)

**Comment by dachafra** [comment]
the problem is solved @ednaru
